# Generated by Django 4.0.6 on 2022-08-19 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frameapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Text',
        ),
    ]
