# Generated by Django 4.0.6 on 2022-08-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frameapp', '0002_rename_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='image',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
    ]
