# Generated by Django 4.0.6 on 2022-08-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frameapp', '0004_image_remove_text_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='my_image'),
        ),
    ]
